package authapi

import (
	"errors"
	"gost/api"
	"gost/auth"
	"gost/auth/cookies"
	"gost/util"
	"log"
	"net/http"

	"gopkg.in/mgo.v2/bson"
)

// Errors generated by then Auth endpoint
var (
	ErrInvalidIDParam = errors.New("The userId parameter is not a valid bson.ObjectId")
	ErrPasswordMatch  = errors.New("The passwords do not match")
)

// AuthAPI defines the API endpoint for user authorization
type AuthAPI int

// AuthModel is a binding model used for receiving the authentication data
type AuthModel struct {
	AppUserID            string          `json:"appUserID"`
	Password             string          `json:"password"`
	PasswordConfirmation string          `json:"passwordConfirmation"`
	ClientDetails        *cookies.Client `json:"clientDetails"`
}

// CreateSession creates a new session for an existing user account
func (a *AuthAPI) CreateSession(params *api.Request) api.Response {
	model := &AuthModel{}

	err := util.DeserializeJSON(params.Body, model)
	if err != nil {
		return api.BadRequest(err)
	}

	if model.Password != model.PasswordConfirmation {
		return api.BadRequest(ErrPasswordMatch)
	}

	if !bson.IsObjectIdHex(model.AppUserID) {
		return api.BadRequest(ErrInvalidIDParam)
	}

	token, err := auth.GenerateUserAuth(bson.ObjectIdHex(model.AppUserID), model.ClientDetails)
	if err != nil {
		return api.BadRequest(err)
	}

	log.Println("TOKEN:", token)
	return api.PlainTextResponse(http.StatusOK, token)
}

// KillSession deletes a session for an existing user account based on
// the session token
func (a *AuthAPI) KillSession(params *api.Request) api.Response {
	return api.BadRequest(errors.New("FUNCTIONALITY NOT IMPLEMENTED"))
}
